project_id = "fnfjegnlplfizcdyavti"
[functions.auto-embed]
enabled = true
verify_jwt = true
import_map = "./functions/auto-embed/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/auto-embed/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/auto-embed/*.html" ]

[functions.nlp-search]
enabled = true
verify_jwt = true
import_map = "./functions/nlp-search/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/nlp-search/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/nlp-search/*.html" ]
